---
boot:
  params:
    locales: fr_FR
  plugins:
    - io.vertigo.core.plugins.resource.classpath.ClassPathResourceResolverPlugin: {}
    - io.vertigo.vega.plugins.webservice.servlet.WebAppContextParamPlugin: {}
    - io.vertigo.core.plugins.analytics.log.SocketLoggerAnalyticsConnectorPlugin: {}
modules:
  io.vertigo.connectors.javalin.JavalinFeatures:
    features:
      - standalone:
  io.vertigo.commons.CommonsFeatures:
    features:
      - script:
    featuresConfig:
      - script.janino:
  io.vertigo.database.DatabaseFeatures:
    features:
      - sql:
    featuresConfig:
      - sql.datasource:
          classname: io.vertigo.database.impl.sql.vendor.postgresql.PostgreSqlDataBase
          source: java:/comp/env/jdbc/DataSource
  io.vertigo.datamodel.DataModelFeatures:
  io.vertigo.datastore.DataStoreFeatures:
    features:
      - cache:
      - entitystore:
      - kvStore:
      - entityMetrics:
    featuresConfig:
      - cache.memory:
      - entitystore.sql:
      - kvStore.berkeley:
          collections: VViewContext;TTL=43200
          dbFilePath: ${java.io.tmpdir}/vertigo-ui/ViewContext
  io.vertigo.datafactory.DataFactoryFeatures:
    featuresConfig:
      - collections.luceneIndex:
  io.vertigo.account.AccountFeatures:
    features:
      - security:
          userSessionClassName: ${package}.user.${projectName}UserSession
    featuresConfig:
  io.vertigo.vega.VegaFeatures:
    features:
        - webservices:
    featuresConfig:
        - webservices.rateLimiting:
        - webservices.security:
        - webservices.javalin:
            apiPrefix: /api
  ${package}.${businessModuleLowerCase}.${businessModule}Features:
initializers:
  - ${package}.boot.I18nResourcesInitializer:
