package lollipop.domain;

import java.util.Arrays;
import java.util.Iterator;

import io.vertigo.core.lang.Generated;
import io.vertigo.dynamo.domain.metamodel.DtFieldName;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DtDefinitions implements Iterable<Class<?>> {

	/**
	 * Enumération des DtDefinitions.
	 */
	public enum Definitions {
		/** Objet de données ApplicationUser. */
		ApplicationUser(lollipop.domain.users.ApplicationUser.class),
		/** Objet de données Casting. */
		Casting(lollipop.domain.people.Casting.class),
		/** Objet de données Commune. */
		Commune(lollipop.domain.movies.Commune.class),
		/** Objet de données Movie. */
		Movie(lollipop.domain.movies.Movie.class),
		/** Objet de données MovieDisplay. */
		MovieDisplay(lollipop.domain.movies.MovieDisplay.class),
		/** Objet de données MovieIndex. */
		MovieIndex(lollipop.domain.movies.MovieIndex.class),
		/** Objet de données OuiNonChoice. */
		OuiNonChoice(lollipop.domain.movies.OuiNonChoice.class),
		/** Objet de données People. */
		People(lollipop.domain.people.People.class),
		/** Objet de données Profil. */
		Profil(lollipop.domain.users.Profil.class),
		/** Objet de données SecurityRole. */
		SecurityRole(lollipop.domain.users.SecurityRole.class),
		/** Objet de données UserAuthentification. */
		UserAuthentification(lollipop.domain.users.UserAuthentification.class)		;

		private final Class<?> clazz;

		private Definitions(final Class<?> clazz) {
			this.clazz = clazz;
		}

		/** 
		 * Classe associée.
		 * @return Class d'implémentation de l'objet 
		 */
		public Class<?> getDtClass() {
			return clazz;
		}
	}

	/**
	 * Enumération des champs de ApplicationUser.
	 */
	public enum ApplicationUserFields implements DtFieldName<lollipop.domain.users.ApplicationUser> {
		/** Propriété 'USR_ID'. */
		usrId,
		/** Propriété 'Last Name'. */
		lastName,
		/** Propriété 'First Name'. */
		firstName,
		/** Propriété 'email'. */
		email,
		/** Propriété 'Profil'. */
		proId	}

	/**
	 * Enumération des champs de Casting.
	 */
	public enum CastingFields implements DtFieldName<lollipop.domain.people.Casting> {
		/** Propriété 'Cast_id'. */
		castId,
		/** Propriété 'Character name'. */
		characterName,
		/** Propriété 'People'. */
		peoId,
		/** Propriété 'Movie'. */
		movId	}

	/**
	 * Enumération des champs de Commune.
	 */
	public enum CommuneFields implements DtFieldName<lollipop.domain.movies.Commune> {
		/** Propriété 'idInsee'. */
		idInsee,
		/** Propriété 'codePostal'. */
		codePostal,
		/** Propriété 'commune'. */
		commune,
		/** Propriété 'departement'. */
		departement	}

	/**
	 * Enumération des champs de Movie.
	 */
	public enum MovieFields implements DtFieldName<lollipop.domain.movies.Movie> {
		/** Propriété 'MOV_ID'. */
		movId,
		/** Propriété 'TITLE'. */
		title,
		/** Propriété 'Released'. */
		released,
		/** Propriété 'Year'. */
		year,
		/** Propriété 'Runtime'. */
		runtime,
		/** Propriété 'Description'. */
		description,
		/** Propriété 'Poster'. */
		poster,
		/** Propriété 'rated'. */
		rated,
		/** Propriété 'lastModified'. */
		lastModified	}

	/**
	 * Enumération des champs de MovieDisplay.
	 */
	public enum MovieDisplayFields implements DtFieldName<lollipop.domain.movies.MovieDisplay> {
		/** Propriété 'id'. */
		movId,
		/** Propriété 'Title'. */
		title	}

	/**
	 * Enumération des champs de MovieIndex.
	 */
	public enum MovieIndexFields implements DtFieldName<lollipop.domain.movies.MovieIndex> {
		/** Propriété 'id'. */
		movId,
		/** Propriété 'Title'. */
		title,
		/** Propriété 'label'. */
		titleSortOnly,
		/** Propriété 'Original Title'. */
		originalTitle,
		/** Propriété 'Synopsis'. */
		synopsis,
		/** Propriété 'Synopsis'. */
		shortSynopsis,
		/** Propriété 'keywords'. */
		keywords,
		/** Propriété 'poster'. */
		poster,
		/** Propriété 'runtime'. */
		runtime,
		/** Propriété 'Movie type'. */
		movieType,
		/** Propriété 'productionYear'. */
		productionYear,
		/** Propriété 'userRating'. */
		userRating,
		/** Propriété 'pressRating'. */
		pressRating,
		/** Propriété 'Camera'. */
		camera	}

	/**
	 * Enumération des champs de OuiNonChoice.
	 */
	public enum OuiNonChoiceFields implements DtFieldName<lollipop.domain.movies.OuiNonChoice> {
		/** Propriété 'Valeur'. */
		key,
		/** Propriété 'Libellé'. */
		libelle	}

	/**
	 * Enumération des champs de People.
	 */
	public enum PeopleFields implements DtFieldName<lollipop.domain.people.People> {
		/** Propriété 'PEO_ID'. */
		peoId,
		/** Propriété 'Last Name'. */
		lastName,
		/** Propriété 'First Name'. */
		firstName,
		/** Propriété 'Peo Name'. */
		peoName,
		/** Propriété 'imdbID'. */
		imdbid	}

	/**
	 * Enumération des champs de Profil.
	 */
	public enum ProfilFields implements DtFieldName<lollipop.domain.users.Profil> {
		/** Propriété 'PRO_ID'. */
		proId,
		/** Propriété 'Label'. */
		label	}

	/**
	 * Enumération des champs de SecurityRole.
	 */
	public enum SecurityRoleFields implements DtFieldName<lollipop.domain.users.SecurityRole> {
		/** Propriété 'SRO_CD'. */
		sroCd,
		/** Propriété 'Label'. */
		label	}

	/**
	 * Enumération des champs de UserAuthentification.
	 */
	public enum UserAuthentificationFields implements DtFieldName<lollipop.domain.users.UserAuthentification> {
		/** Propriété 'AUTH_ID'. */
		authId,
		/** Propriété 'Login'. */
		login,
		/** Propriété 'Password'. */
		password,
		/** Propriété 'Application user'. */
		usrId	}

	/** {@inheritDoc} */
	@Override
	public Iterator<Class<?>> iterator() {
		return new Iterator<Class<?>>() {
			private Iterator<Definitions> it = Arrays.asList(Definitions.values()).iterator();

			/** {@inheritDoc} */
			@Override
			public boolean hasNext() {
				return it.hasNext();
			}

			/** {@inheritDoc} */
			@Override
			public Class<?> next() {
				return it.next().getDtClass();
			}
		};
	}
}
